version: "3"

volumes:
  archive:
  data:
    external: true

networks:
  proxy:

services:
  extractor:
    image: extractor:latest
    build:
      context: extractor
    volumes:
      - archive:/archive
      - data:/data

  
  uploadserver:
    image: uploadserver:latest
    build:
      context: webserver-rocket
    links:
      - extractor
    volumes:
      - data:/data
    expose:
      - 8000
    networks:
      - proxy

  proxy:
    image: nginx:alpine
    ports:
      - 5443:443
    links:
      - uploadserver
    volumes:
      - ./nginx/auth:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - proxy

  cleanup:
    image: alpine:3.6
    command: ["crond", "-f", "-d", "8"]
    links:
      - extractor
    volumes:
      - ./cronjobs:/etc/crontabs/root:ro
      - data:/data
      - archive:/archive

