version: "3"

volumes:
  archive:
  data:

services:
  extractor:
    image: extractor:latest
    build:
      context: extractor
    volumes:
      - archive:/archive
      - data:/data

  
  uploadserver:
    image: uploadserver:latest
    build:
      context: webserver-rocket
    volumes:
      - data:/data
    ports:
      - 8080:8000