name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-extractor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the extractor image
      run: docker build . --file extractor/Dockerfile --tag extractor:$(date +%F)
  build-rocketserver:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the extractor image
      run: docker build . --file webserver-rocket/Dockerfile --tag uploadserver:$(date +%F)
